spring:
  config:
    activate:
      on-profile: web-ext
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  mvc:
    # 解决传日期参数报 400 转换错误问题
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    # 设置 json 日期序列化输出格式相对北京时间与格林尼治时间有八个小时的时差，设置偏移量
    time-zone: GMT+8
    # 格式化 json 输出的时间问题，将格林尼治时间进行转换
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
  main:
    allow-bean-definition-overriding: true
mybatis-flex:
  global-config:
    deleted-value-of-logic-delete: NOW()
    normal-value-of-logic-delete: null